# Generated by Django 4.2 on 2023-04-18 00:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_l', models.ImageField(blank=True, upload_to='image_upload/')),
                ('photo_m', models.ImageField(blank=True, upload_to='image_upload/')),
                ('photo_s', models.ImageField(blank=True, upload_to='image_upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('catch', models.CharField(blank=True, max_length=512)),
                ('wifi', models.CharField(max_length=32)),
                ('child', models.CharField(max_length=32)),
                ('budget', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=32)),
                ('sub_genre', models.CharField(max_length=64)),
                ('station_name', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('restaurant_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommend_restaurant.restaurantphoto')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'restaurant')},
                'index_together': {('user', 'restaurant')},
            },
        ),
    ]
