# Generated by Django 4.2 on 2023-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('catch', models.CharField(max_length=512)),
                ('wifi', models.CharField(max_length=32)),
                ('child', models.CharField(max_length=32)),
                ('budget', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=32)),
                ('sub_genre', models.CharField(max_length=64)),
            ],
        ),
    ]
