# Generated by Django 4.2 on 2023-04-15 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_restaurants', '0004_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_l', models.ImageField(blank=True, upload_to='image_upload/')),
                ('photo_m', models.ImageField(blank=True, upload_to='image_upload/')),
                ('photo_s', models.ImageField(blank=True, upload_to='image_upload/')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommend_restaurants.restaurantphoto'),
        ),
    ]
