# Generated by Django 4.2 on 2023-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_restaurants', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='station_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
